language: ruby
rvm:
  - 2.3.1
services:
  - mysql
before_script:
  - mysql -e 'create database eecshelp_test;'
env:
    global:
      - EECSHELP_TEST_DATABASE_HOST=""
      - EECSHELP_TEST_DATABASE=eecshelp_test
      - EECSHELP_TEST_DATABASE_USERNAME=travis
      - EECSHELP_TEST_DATABASE_PASSWORD=""
addons:
    code_climate:
        repo_token: 1cf5f43943029d7d3527fdf79206a87cd36fe0a87a49d11eb3a3ff89ab64fd11
