version: '2'
services:
  web:
    build: .
    env_file:
      - web-variables.env
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/eecshelp
    ports:
      - "3000:3000"
